/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Coin, Empty, CollectionParams } from "./BaseFactory.types";
export interface BaseFactoryMessage {
    contractAddress: string;
    sender: string;
    createMinter: ({ collectionParams, initMsg }: {
        collectionParams: CollectionParams;
        initMsg?: Empty;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class BaseFactoryMessageComposer implements BaseFactoryMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    createMinter: ({ collectionParams, initMsg }: {
        collectionParams: CollectionParams;
        initMsg?: Empty;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
