/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Coin } from "./Whitelist.types";
export interface WhitelistMessage {
    contractAddress: string;
    sender: string;
    updateStartTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateEndTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    addMembers: ({ toAdd }: {
        toAdd: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    removeMembers: ({ toRemove }: {
        toRemove: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updatePerAddressLimit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    increaseMemberLimit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateAdmins: ({ admins }: {
        admins: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    freeze: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class WhitelistMessageComposer implements WhitelistMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateStartTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateEndTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    addMembers: ({ toAdd }: {
        toAdd: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    removeMembers: ({ toRemove }: {
        toRemove: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updatePerAddressLimit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    increaseMemberLimit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateAdmins: ({ admins }: {
        admins: string[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    freeze: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
