/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ContractBase, IContractConstructor, IEmptyClient } from "./contractContextBase";
import { BaseFactoryClient } from "./BaseFactory.client";
import { BaseFactoryMessageComposer } from "./BaseFactory.message-composer";
export declare class BaseFactory extends ContractBase<BaseFactoryClient, IEmptyClient, BaseFactoryMessageComposer> {
    constructor({ address, cosmWasmClient, signingCosmWasmClient }: IContractConstructor);
}
