/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ContractBase, IContractConstructor, IEmptyClient } from "./contractContextBase";
import { BaseMinterClient } from "./BaseMinter.client";
import { BaseMinterMessageComposer } from "./BaseMinter.message-composer";
export declare class BaseMinter extends ContractBase<BaseMinterClient, IEmptyClient, BaseMinterMessageComposer> {
    constructor({ address, cosmWasmClient, signingCosmWasmClient }: IContractConstructor);
}
