/**
* This file and any referenced files were automatically generated by @cosmwasm/ts-codegen@0.34.0
* DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
* and run the transpile command or yarn proto command to regenerate this bundle.
*/
import React from 'react';
import { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';
import { IContractsContext } from './contractContextProviders';
interface ContractsConfig {
    address: string | undefined;
    getCosmWasmClient: () => Promise<CosmWasmClient>;
    getSigningCosmWasmClient: () => Promise<SigningCosmWasmClient>;
}
export declare const ContractsProvider: ({ children, contractsConfig, }: {
    children: React.ReactNode;
    contractsConfig: ContractsConfig;
}) => any;
export declare const useContracts: () => IContractsContext;
export {};
