/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Coin } from "./BaseMinter.types";
export interface BaseMinterMessage {
    contractAddress: string;
    sender: string;
    mint: ({ tokenUri }: {
        tokenUri: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateStartTradingTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class BaseMinterMessageComposer implements BaseMinterMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    mint: ({ tokenUri }: {
        tokenUri: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateStartTradingTime: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
