/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./SG721Base.client";
import * as _7 from "./VendingMinter.client";
import * as _8 from "./VendingMinter.message-composer";
import * as _10 from "./Whitelist.client";
import * as _11 from "./Whitelist.message-composer";
export declare namespace contracts {
    const SG721Base: {
        SG721BaseQueryClient: typeof _1.SG721BaseQueryClient;
    };
    const VendingFactory: {};
    const VendingMinter: {
        VendingMinterMessageComposer: typeof _8.VendingMinterMessageComposer;
        VendingMinterQueryClient: typeof _7.VendingMinterQueryClient;
        VendingMinterClient: typeof _7.VendingMinterClient;
    };
    const Whitelist: {
        WhitelistMessageComposer: typeof _11.WhitelistMessageComposer;
        WhitelistQueryClient: typeof _10.WhitelistQueryClient;
        WhitelistClient: typeof _10.WhitelistClient;
    };
}
