/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
export interface SplitsMessage {
    contractAddress: string;
    sender: string;
    updateAdmin: ({ admin }: {
        admin?: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    distribute: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class SplitsMessageComposer implements SplitsMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateAdmin: ({ admin }: {
        admin?: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    distribute: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
