/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./SG721Base.types";
import * as _1 from "./SG721Base.client";
import * as _2 from "./SG721Base.message-composer";
import * as _3 from "./SG721MetadataOnchain.types";
import * as _4 from "./SG721MetadataOnchain.client";
import * as _5 from "./SG721MetadataOnchain.message-composer";
import * as _6 from "./Sg721Nt.types";
import * as _7 from "./Sg721Nt.client";
import * as _8 from "./Sg721Nt.message-composer";
import * as _9 from "./Sg721Updatable.types";
import * as _10 from "./Sg721Updatable.client";
import * as _11 from "./Sg721Updatable.message-composer";
import * as _12 from "./BaseFactory.types";
import * as _13 from "./BaseFactory.client";
import * as _14 from "./BaseFactory.message-composer";
import * as _15 from "./VendingFactory.types";
import * as _16 from "./VendingFactory.client";
import * as _17 from "./VendingFactory.message-composer";
import * as _18 from "./BaseMinter.types";
import * as _19 from "./BaseMinter.client";
import * as _20 from "./BaseMinter.message-composer";
import * as _21 from "./VendingMinter.types";
import * as _22 from "./VendingMinter.client";
import * as _23 from "./VendingMinter.message-composer";
import * as _24 from "./VendingMinterWlFlex.types";
import * as _25 from "./VendingMinterWlFlex.client";
import * as _26 from "./VendingMinterWlFlex.message-composer";
import * as _27 from "./SgEthAirdrop.types";
import * as _28 from "./SgEthAirdrop.client";
import * as _29 from "./SgEthAirdrop.message-composer";
import * as _30 from "./Splits.types";
import * as _31 from "./Splits.client";
import * as _32 from "./Splits.message-composer";
import * as _33 from "./Whitelist.types";
import * as _34 from "./Whitelist.client";
import * as _35 from "./Whitelist.message-composer";
import * as _36 from "./WhitelistFlex.types";
import * as _37 from "./WhitelistFlex.client";
import * as _38 from "./WhitelistFlex.message-composer";
import * as _39 from "./WhitelistImmutable.types";
import * as _40 from "./WhitelistImmutable.client";
import * as _41 from "./WhitelistImmutable.message-composer";
import * as _42 from "./Marketplace.types";
import * as _43 from "./Marketplace.client";
import * as _44 from "./Marketplace.message-composer";
import * as _45 from "./ReserveAuction.types";
import * as _46 from "./ReserveAuction.client";
import * as _47 from "./ReserveAuction.message-composer";
export namespace contracts {
  export const SG721Base = { ..._0,
    ..._1,
    ..._2
  };
  export const SG721MetadataOnchain = { ..._3,
    ..._4,
    ..._5
  };
  export const Sg721Nt = { ..._6,
    ..._7,
    ..._8
  };
  export const Sg721Updatable = { ..._9,
    ..._10,
    ..._11
  };
  export const BaseFactory = { ..._12,
    ..._13,
    ..._14
  };
  export const VendingFactory = { ..._15,
    ..._16,
    ..._17
  };
  export const BaseMinter = { ..._18,
    ..._19,
    ..._20
  };
  export const VendingMinter = { ..._21,
    ..._22,
    ..._23
  };
  export const VendingMinterWlFlex = { ..._24,
    ..._25,
    ..._26
  };
  export const SgEthAirdrop = { ..._27,
    ..._28,
    ..._29
  };
  export const Splits = { ..._30,
    ..._31,
    ..._32
  };
  export const Whitelist = { ..._33,
    ..._34,
    ..._35
  };
  export const WhitelistFlex = { ..._36,
    ..._37,
    ..._38
  };
  export const WhitelistImmutable = { ..._39,
    ..._40,
    ..._41
  };
  export const Marketplace = { ..._42,
    ..._43,
    ..._44
  };
  export const ReserveAuction = { ..._45,
    ..._46,
    ..._47
  };
}