/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { InstantiateMsg, ExecuteMsg, QueryMsg, Uint64, Addr, ConfigResponse, Config, Boolean, PerAddressLimitResponse } from "./WhitelistImmutable.types";