/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.13.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./SG721Base.types";
import * as _1 from "./SG721Base.client";
import * as _2 from "./SG721Base.message-composer";
import * as _3 from "./VendingFactory.types";
import * as _4 from "./VendingFactory.client";
import * as _5 from "./VendingFactory.message-composer";
import * as _6 from "./VendingMinter.types";
import * as _7 from "./VendingMinter.client";
import * as _8 from "./VendingMinter.message-composer";
import * as _9 from "./Whitelist.types";
import * as _10 from "./Whitelist.client";
import * as _11 from "./Whitelist.message-composer";
export namespace contracts {
  export const SG721Base = { ..._0,
    ..._1,
    ..._2
  };
  export const VendingFactory = { ..._3,
    ..._4,
    ..._5
  };
  export const VendingMinter = { ..._6,
    ..._7,
    ..._8
  };
  export const Whitelist = { ..._9,
    ..._10,
    ..._11
  };
}