/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor, IEmptyClient } from "./contractContextBase";
import { BaseFactoryClient } from "./BaseFactory.client";
import { BaseFactoryMsgComposer } from "./BaseFactory.message-composer";
export class BaseFactory extends ContractBase<BaseFactoryClient, IEmptyClient, BaseFactoryMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, BaseFactoryClient, undefined, BaseFactoryMsgComposer);
  }

}