/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { ReserveAuctionClient, ReserveAuctionQueryClient } from "./ReserveAuction.client";
import { ReserveAuctionMsgComposer } from "./ReserveAuction.message-composer";
export class ReserveAuction extends ContractBase<ReserveAuctionClient, ReserveAuctionQueryClient, ReserveAuctionMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, ReserveAuctionClient, ReserveAuctionQueryClient, ReserveAuctionMsgComposer);
  }

}