/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { SgEthAirdropClient, SgEthAirdropQueryClient } from "./SgEthAirdrop.client";
import { SgEthAirdropMessageComposer } from "./SgEthAirdrop.message-composer";
export class SgEthAirdrop extends ContractBase<SgEthAirdropClient, SgEthAirdropQueryClient, SgEthAirdropMessageComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, SgEthAirdropClient, SgEthAirdropQueryClient, SgEthAirdropMessageComposer);
  }

}