/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { VendingMinterClient, VendingMinterQueryClient } from "./VendingMinter.client";
import { VendingMinterMsgComposer } from "./VendingMinter.message-composer";
export class VendingMinter extends ContractBase<VendingMinterClient, VendingMinterQueryClient, VendingMinterMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, VendingMinterClient, VendingMinterQueryClient, VendingMinterMsgComposer);
  }

}