/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { VendingMinterWlFlexClient, VendingMinterWlFlexQueryClient } from "./VendingMinterWlFlex.client";
import { VendingMinterWlFlexMsgComposer } from "./VendingMinterWlFlex.message-composer";
export class VendingMinterWlFlex extends ContractBase<VendingMinterWlFlexClient, VendingMinterWlFlexQueryClient, VendingMinterWlFlexMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, VendingMinterWlFlexClient, VendingMinterWlFlexQueryClient, VendingMinterWlFlexMsgComposer);
  }

}